In [1]:
import numpy as np

In [2]:
a = np.zeros((2,2)) 

In [3]:
print(a)

[[0. 0.]
 [0. 0.]]


In [4]:
b = np.ones((1, 2))

In [5]:
print(b)

[[1. 1.]]


In [6]:
c = np.full((2, 2), 7)

In [7]:
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2)

In [9]:
print(d)

[[1. 0.]
 [0. 1.]]


In [10]:
e = np.random.random((2,2)) 

In [11]:
print(e)

[[0.2151834  0.11612139]
 [0.91631781 0.72120803]]
