In [1]:
import numpy as np

In [2]:
a = np.zeros((6,6))

In [3]:
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
for l in range(6):
    for c in range(6):
        a[l][c] = c + 10 * l
        # debug
        print("[" + str(l) + "]" + "[" + str(c) + "]" + " = " + str(int(a[l][c])))

[0][0] = 0
[0][1] = 1
[0][2] = 2
[0][3] = 3
[0][4] = 4
[0][5] = 5
[1][0] = 10
[1][1] = 11
[1][2] = 12
[1][3] = 13
[1][4] = 14
[1][5] = 15
[2][0] = 20
[2][1] = 21
[2][2] = 22
[2][3] = 23
[2][4] = 24
[2][5] = 25
[3][0] = 30
[3][1] = 31
[3][2] = 32
[3][3] = 33
[3][4] = 34
[3][5] = 35
[4][0] = 40
[4][1] = 41
[4][2] = 42
[4][3] = 43
[4][4] = 44
[4][5] = 45
[5][0] = 50
[5][1] = 51
[5][2] = 52
[5][3] = 53
[5][4] = 54
[5][5] = 55


In [5]:
print(a)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]
 [30. 31. 32. 33. 34. 35.]
 [40. 41. 42. 43. 44. 45.]
 [50. 51. 52. 53. 54. 55.]]


In [6]:
a[0, 3:5]

array([3., 4.])

In [7]:
a[4:, 4:]

array([[44., 45.],
       [54., 55.]])

In [8]:
a[:, 2]

array([ 2., 12., 22., 32., 42., 52.])

In [9]:
a[2::2, ::2]

array([[20., 22., 24.],
       [40., 42., 44.]])