In [1]:
# Exemplo 1

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
x

array([[1., 2.],
       [3., 4.]])

In [4]:
y = np.array([[5,6],[7,8]], dtype=np.float64)
y

array([[5., 6.],
       [7., 8.]])

In [5]:
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [6]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [7]:
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [8]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [9]:
print(x * y)

[[ 5. 12.]
 [21. 32.]]


In [10]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [11]:
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [14]:
# Exemplo 2

In [15]:
import numpy as np

In [16]:
x = np.array([[1,2],[3,4]])

In [21]:
y = np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [22]:
v = np.array([9,10])
v

array([ 9, 10])

In [23]:
w = np.array([11, 12])
w

array([11, 12])

In [20]:
y.T

array([[5, 7],
       [6, 8]])

In [24]:
print(v.dot(w))

219


In [25]:
print(np.dot(v, w))

219


In [26]:
print(x.dot(v))

[29 67]


In [27]:
print(np.dot(x, v))

[29 67]


In [28]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [29]:
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [30]:
# Exemplo 3

In [31]:
import numpy as np

In [32]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [33]:
print(np.sum(x))  

10


In [34]:
print(np.sum(x, axis=0)) 

[4 6]


In [35]:
print(np.sum(x, axis=1))  

[3 7]


In [36]:
# Exemplo 4

In [37]:
import numpy as np

In [38]:
x = np.array([[1,2], [3,4]])

In [39]:
print(x)    

[[1 2]
 [3 4]]


In [40]:
print(x.T)  

[[1 3]
 [2 4]]


In [41]:
v = np.array([1,2,3])

In [42]:
print(v)    

[1 2 3]


In [43]:
print(v.T)

[1 2 3]
