In [1]:
# Exemplo 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [4]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [7]:
print(a[0, 1])

2


In [8]:
b[0, 0] = 77     

In [9]:
print(a[0, 1])

77


In [10]:
# Exemplo 2

In [11]:
import numpy as np

In [14]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
print(a[[0, 1, 2], [0, 1, 0]])  

[1 4 5]


In [15]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  

[1 4 5]


In [16]:
print(a[[0, 0], [1, 1]])  

[2 2]


In [17]:
print(np.array([a[0, 1], a[0, 1]])) 

[2 2]


In [18]:
# Data types

In [19]:
import numpy as np

In [20]:
x = np.array([1, 2])   

In [21]:
print(x.dtype)

int64


In [22]:
x = np.array([1.0, 2.0])   

In [23]:
print(x.dtype)             

float64


In [24]:
x = np.array([1, 2], dtype=np.int64)   

In [25]:
print(x.dtype)

int64
